config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'

  root 'homepage#index'
  resources :artists
  get 'listings/index'
  #get '/index' => 'homepage#index'
  #resources :url_uploads


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :events, :dependent => :destroy
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end
  def new
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def create
    artist_name = params.require(:artist)[:artist_name]
    mechanize = mechanize(artist_name)
    url = mechanize.mechanize
    if url.nil? == true
      flash[:notice] = "Couldn't find this artist"
      redirect_to new_artist_path
    else
      artist = Artist.create(artist_name: artist_name, url: url)
      redirect_to artist_path(id: artist.id)
      #if artist.create fails do something
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to artists_path
  end

  private

  def mechanize(artist_name)
    MechanizeService.new(artist_name)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    # TO DO - Refresh every hour? or if new artist added?
    refresh_listings
  end

  def refresh_listings
    # TO DO - move into a refresh service?
    Artist.all.each do |artist|
      new_noko = NokogiriObject.new(artist)
      noko = new_noko.nokogiri_object
      new_scrape = ScraperService.new(artist, noko)
      new_scrape.scrapeRA
    end
    @locations = save_locations_in_table(Event.all)
  end

  def title(page_title)
    content_for :title, "Listings"
  end

#instead of location list, create new model that belongs to event
  def save_locations_in_table(events)
    location_list = Array.new
    Event.all.each do |e|
      location = e.location .split(',').last.lstrip
      location_list << location unless location_list.include?(location)
    end
    location_list
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/views/artists/index.html.erb
<body class="background">
<% title "Listing artists" %>

<div class="new-artist-form">
<div class="table">
<table>
  <tr>
    <th>Artist</th>
    <th>Url</th>
  </tr>

  <% if Artist.nil? == false %>
  <% Artist.all.each do |artist| %>
    <tr>
      <td><%= artist.artist_name %></td>
      <td><%= artist.url %></td>
      <td><%= link_to 'Show', artist_path(artist) %></td>
      <td><%= link_to 'Destroy', artist_path(artist),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </tr>
  <% end %>
  <% end %>
</table>
</div>
</div>

</body>

app/views/artists/new.html.erb
<body class="background">
<% title "Add a new artist" %>

<div class ="new-artist-form" id="new">
  <%= form_with scope: :artist, url: artists_path, local: true do |form| %>
    <p class="input-text">
      <%= form.text_field :artist_name, placeholder: "Artist name", :size => 60 %>
    </p>

    <p class="submit-button">
      <%= form.submit class: 'btn btn-default'%>
    </p>
  <% end %>
</div>


</body>

app/views/artists/show.html.erb
<body class="background">
<% title "Saved" %>

<div class ="new-artist-form">
<p>
  <strong>Artist:</strong>
  <%= @artist.artist_name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @artist.url %>
</p>
</div>


</body>

app/views/homepage/index.html.erb
<body class="home">
<div class="main-title">
  <h1 id="home-age-title" >UK Event Tracker</h1>
</div>
<div class="links">
  <li><a id="listings"><%= link_to 'Listings', listings_index_path %></a></li>
  <li><a id="uploads"><%= link_to 'New artist', new_artist_path %></a></li>
</div>
<a id="source" href="https://www.freepik.com/free-vector/techno-party_761404.htm">Background image: Designed by Freepik</a>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a><%= link_to "Home", homepage_index_path %></a>
      <a><%= link_to "Listings", listings_index_path%></a>
      <a><%= link_to "Add", new_artist_path %></a>
      <a><%= link_to "Edit", artists_path %></a>
    </div>
    
    <div id="main">
        <div class="menu-button">
          <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; </span>
        </div>
        <div class="centered-content">
          <div class="page-title">
            <%= content_for?(:title) ? yield(:title) : 'Personalised Event Lister' %>
          </div>
          <div class="main-content">
            <%= yield %>
          </div>
        </div>
    </div>


  </body>
</html>

app/views/listings/index.html.erb
<body class="background">
<div class="listings-content">

    <% title "Listings" %>


  <div class="listings">
    <h3> Click to expand list of events </h3>
    <%= select "obj", "test", @locations.each_with_index.map {|name, index| [name,index]} %>

  <% Artist.all.each do |artist| %>
    <div class="tab">
      <input id="<%= artist.artist_name %>" type="checkbox" name="tabs">
      <label id="listings-label" for="<%= artist.artist_name %>"><%= artist.artist_name %></label>
      <div class="tab-content">
        <% events = Event.where("artist_id = #{artist.id}") %>
        <% events.each do |event| %>
        <div class="event">
          <p>  <%= event.event_title %></p>
          <p>  <%= event.location %></p>
          <p>  <%= event.event_date %></p>

        </div>

        </br>
        <% end %>
        </br>
      </div>
    </div>
  <% end %>
  </div>
</div>

</body>